city_data = {
    "Munich": {
        "infected": 6624,
        "dead": 215,
        "healed": 6119,
        "total": 1400000,
        "type": "Metropole",
    },
    "Zurich": {
        "infected": 931,
        "dead": 33,
        "healed": 887,
        "total": 400000,
        "type": "Metropole",
    },
    "Montpellier": {
        "infected": 209,
        "dead": 29,
        "healed": 167,
        "total": 270000,
        "type": "Stadt",
    },
    "Barcelona": {
        "infected": 6155,
        "dead": 1190,
        "healed": 5502,
        "total": 5500000,
        "type": "Metropole"
    },
    "Lyon": {
        "infected": 1219,
        "dead": 181,
        "healed": 810,
        "total": 513000,
        "type": "Stadt",
    },
    "Geneva": {
        "infected": 5251,
        "dead": 286,
        "healed": 4962,
        "total": 499000,
        "type": "Stadt",
    },
    "Colmar": {
        "infected": 454,
        "dead": 88,
        "healed": 297,
        "total": 70000,
        "type": "Land",
    },
    "Avignon": {
        "infected": 63,
        "dead": 7,
        "healed": 42,
        "total": 92000,
        "type": "Stadt",
    },
    "Ceret": {
        "infected": 7,
        "dead": 1,
        "healed": 6,
        "total": 8000,
        "type": "Land",
    },
    "Mende": {
        "infected": 4,
        "dead": 1,
        "healed": 3,
        "total": 12000,
        "type": "Stadt",
    },
    "Titisee-Neustadt": {
        "infected": 54,
        "dead": 0,
        "healed": 0,
        "total": 12000,
        "type": "Land",
    },
    "Mayrhofen": {
        "infected": 203,
        "dead": 4,
        "healed": 98,
        "total": 4000,
        "type": "Land",
    },
    "Bozen": {
        "infected": 710,
        "dead": 76,
        "healed": 620,
        "total": 107000,
        "type": "Land",
    },
    "Digne": {
        "infected": 16,
        "dead": 1,
        "healed":3,
        "total": 16000,
        "type": "Land",
    },
    "Girona": {
        "infected": 6075,
        "dead": 567,
        "healed":2620,
        "total": 760000,
        "type": "Land",
    },
    "Rodez": {
        "infected": 37,
        "dead": 5,
        "healed":30,
        "total": 24000,
        "type": "Camping",
    },
    "Chamonix": {
        "infected": 11,
        "dead": 2,
        "healed":8,
        "total": 9000,
        "type": "Land",
    },
    "St.Moritz": {
        "infected": 25,
        "dead": 2,
        "healed":23,
        "total": 5000,
        "type": "Land",
    },
    "Genoa": {
        "infected": 3770,
        "dead": 416,
        "healed":3305,
        "total": 590000,
        "type": "Stadt",
    },
    "Marseille": {
        "infected": 209,
        "dead": 29,
        "healed":167,
        "total": 270000,
        "type": "Stadt",
    },
    "Bayonne": {
        "infected": 20,
        "dead": 2,
        "healed":17,
        "total": 51000,
        "type": "Stadt",
    },
    "Bordeaux": {
        "infected": 686,
        "dead": 77,
        "healed":467,
        "total": 250000,
        "type": "Stadt",
    },
    "Saint Etienne": {
        "infected": 301,
        "dead": 54,
        "healed":207,
        "total": 170000,
        "type": "Land",
    },
    "Mailand": {
        "infected": 12998,
        "dead": 2318,
        "healed":8732,
        "total": 1400000,
        "type": "Metropole",
    },
    "Paris": {
        "infected": 9039,
        "dead": 1738,
        "healed":5947,
        "total": 2148000,
        "type": "Metropole",
    },
    "Strasbourg": {
        "infected": 2517,
        "dead": 464,
        "healed":1725,
        "total": 277000,
        "type": "Stadt",
    },
}
